# Generated by Django 5.1.2 on 2024-10-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myappp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='xeber_yukle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path_yukle', models.CharField(max_length=200)),
                ('category_name_yukle', models.CharField(max_length=200)),
                ('name_yukle', models.CharField(max_length=200)),
                ('description_yukle', models.CharField(max_length=200)),
            ],
        ),
    ]
